version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: ./Backend/Dockerfile
    ports:
      - "3000:3000"

  backend:
    build:
      context: .
      dockerfile: ./Frontend/Dockerfile
    ports:
      - "3001:3001"